### ISSUE TITLE
Go Version: 16.10.0. java.io.FileNotFoundException

### ISSUE THREAD

**Issue by DylanGraham** [jmnarloch/gocd-gradle-plugin#10]
Hi,
On a Fedora 24 system, the `go` user runs the `go-server` and `go-agent`.
This user has a home directory of `/var/go`.
I believe that's why the gocd-gradle-plugin is looking in this location for the gradle wrapper as shown:
`java.io.FileNotFoundException: /var/go/.gradle/wrapper/dists/gradle-2.14.1-all/8bnwg5hd3w55iofp58khbp6yv/gradle-2.14.1-all.zip.lck (No such file or directory)`

Is there an environment variable to adjust just the base home directory from `/var/go` to my user?
I don't want to add more than `/home/dylan` as the other parts of the path will change as gradle is updated.
Thanks

**Comment by DylanGraham** [comment]
Resolved with `GRADLE_USER_HOME`

**Comment by ppardeep91** [comment]
how you resolved this using GRADLE_USER_HOME?

**Comment by DylanGraham** [comment]
@ppardeep91 I set it to `$HOME/.gradle`
