### ISSUE TITLE
Can we have a working directory for gradle/gradlew task to run

### ISSUE THREAD

**Issue by bharathcp** [jmnarloch/gocd-gradle-plugin#4]
I have multiple git materials for my pipeline which forces me to add working directories. Since gradle plugin does not have working directories, it does not find the gradlew or build.gradle.
Please add a feature to define working directory.

**Comment by ashrayme** [comment]
+1

Came here looking for info on the same.

**Comment by bharathcp** [comment]
The pull request #6 should fix this. Hope it gets merged :)

**Comment by jmnarloch** [comment]
You know that gradle has -p option for setting the path? https://docs.gradle.org/current/userguide/gradle_command_line.html
This can be done in the current version with additional build properties.

**Comment by bharathcp** [comment]
Agreed. But it would not work for gradlew commands.

**Comment by jmnarloch** [comment]
Ok, I'm going to test this during fallowing days and prepare the release by the end of the week.
