### ISSUE TITLE
gocd-gradle-plugin v1.0.4 does not work with gocd v16.6.0

### ISSUE THREAD

**Issue by ghost** [jmnarloch/gocd-gradle-plugin#9]
I get the following error (in the UI) when using v1.0.4 of the gocd-gradle-plugin with gocd v16.6.0:

```
Plugin with ID (gocd-gradle-plugin-1.0.4.jar) is not valid: XML Schema validation of Plugin Descriptor(plugin.xml) failed. Cause: cvc-datatype-valid.1.2.1: '1.0.4-SNAPSHOT' is not a valid value for 'integer'.
```

This issue is actually fixed in commit 4a90c631aa2d3d94119c2f1a50f0c3fe91a064f0 (I've verified by opening up the .jar, changing the plugin.xml and reloading the server). Likely we just need to spin a new release here.

**Comment by jmnarloch** [comment]
Done, I've released version 1.0.5, https://github.com/jmnarloch/gocd-gradle-plugin/releases

**Comment by ghost** [comment]
I'll verify and let you know.

**Comment by ghost** [comment]
Confirmed. That fixed the issue. Thanks for the prompt response.
